---
- name: install docker registry
  hosts: node1.mariadb.mate.solutions

  roles:
#    - { role: docker-registry-centos, when: ansible_distribution == 'Centos' }
    - docker-registry
  environment: "{{proxy_env}}"
