---
- name: install addtional system packages and pip packages
  hosts: all:!localhost:!source
  vars:
    #this is needed to prepare vm's for python3 also for ansible
    
  roles:
    - packages-req

  environment: "{{proxy_env}}"
