---
ansible_python_interpreter: /usr/bin/python3

packages:
  - python3
  - python3-setuptools
  - mysql-client
  - python3-pip
  - net-tools

pip_packages:
  - docker

dockerfiles:
  - mariadb
  - icinga2
  - icingaweb2

docker:
  registry: "registry.icinga2.mate.solutions:5000"

virtual_ipaddress: 192.168.90.10
interface_for_vip: ens3

db_root_password: 123
db_icinga_name: icinga
db_icinga_user: icinga
db_icinga_password: icinga123

icinga_ticketsalt: c0721e57b3694d09de16181e725d0375
