---
packages:
  - python3
  - python3-setuptools
  - mysql-client
  - python3-pip

pip_packages:
  - docker-py

dockerfiles:
  - mariadb
  - icinga2
  - icingaweb2

docker:
  registry: "registry.icinga2.mate.solutions:5000"

ansible_python_interpreter: /usr/bin/python3

db_root_password: 123
db_icinga_name: icinga
db_icinga_user: icinga
db_icinga_password: icinga123
