---
#ICINGA2

#TEMPORARY ensure that the config dir for icinga2 is empty
- name: TEMPORARY ensure that the config dir for icinga2 is empty
  file:
    path: /dir-config/icinga2
    state: absent

#prepare config directory in two steps create it and copy
#prepared configuration files from central location
- name: prepare config directories
  file:
    path: /dir-config/{{item}}
    state: directory
    owner: root
    group: root
    mode: 0750
  with_items:
    - icinga2
    - icinga2-ca
    - icingaweb2
    - apache2

- name: copy the config files
  copy:
    src: "{{ playbook_dir }}/docker/{{item}}/configs/{{item}}-cnf-files/"
    dest: /dir-config/{{item}}
  with_items:
#    - icinga2
    - icingaweb2

- name: copy the config files for apache
  copy:
    src: "{{ playbook_dir }}/docker/icingaweb2/configs/apache2-cnf-files/"
    dest: /dir-config/apache2

# create the data volume for icinga2 communication
- name: check if icinga2_cmd exists - volume for icinga2 communication
  command: docker volume inspect icinga2_cmd
  register: icinga2_cmd_exists
  failed_when: false

- name: create volume icinga2_cmd - volume for icinga2 communication
  command: docker volume create --name icinga2_cmd
  when: icinga2_cmd_exists is failed
